[WIP] Added Unitsml::Formula to Math conversion methods
unitsml/unitsml-ruby pull request #11
Opened 2023-03-20 16:09 UTC by suleman-uzair

[WIP] Added **Unitsml** to **MathML**, **Latex** conversion methods.

2023-04-11 01:43 UTC, ronaldtse commented on lib/unitsml/utility.rb
> +          <Unit xmlns="#{UNITSML_NS}" xml:id="#{unit_id(norm_text)}"#{dims ? " dimensionURL=\"##{dim_id(dims)}\"" : ""}>
@suleman-uzair can we not have handcrafted XML?

2023-04-11 01:43 UTC, ronaldtse commented on lib/unitsml/utility.rb
> +          </Dimension>
No handcrafted XML please.

2023-04-11 01:43 UTC, ronaldtse commented on lib/unitsml/utility.rb
> +        %(<#{dim[:dimension]} symbol="#{dim[:symbol]}" powerNumerator="#{float_to_display(dim[:exponent])}"/>)
No handcrafted XML please.

2023-04-11 01:43 UTC, ronaldtse commented on lib/unitsml/utility.rb
> +              <PrefixSymbol type="HTML">#{p&.to_html}</PrefixSymbol>
No handcrafted XML please.

2023-04-11 01:43 UTC, ronaldtse commented on lib/unitsml/utility.rb
> +          </Dimension>
No handcrafted XML please.

2023-04-11 01:43 UTC, ronaldtse commented on lib/unitsml/utility.rb
> +          </Quantity>
No handcrafted XML please.

2023-04-11 01:44 UTC, ronaldtse commented on lib/unitsml/utility.rb
> +          ret += %(<QuantityName xml:lang="en-US">#{q}</QuantityName>)
No handcrafted XML please.

2023-04-11 01:44 UTC, ronaldtse commented on lib/unitsml/formula.rb
> +        #{Utility.quantity(@norm_text, explicit_value&.dig(:quantity))}
No handcrafted XML please.

2023-04-11 01:44 UTC, ronaldtse requested changes
No handcrafted XML please

2023-05-10 11:04 UTC, suleman-uzair commented
As you suggested, we have implemented support for **Ox** for **XML** conversion. However, it's important to note that the conversion of **MathML** and **HTML** is different. The **MathML** and **HTML** conversion data are available in **unitsdb**, and we are currently using this data for the conversion process. There are two important points to mention:
1. We can use string interpolation for the conversion process(`already implemented`).
2. We can use the **Ox** parse method to parse the _unitsdb_ output, which includes the values of both the MathML and **HTML** keys in the `units.yaml` file. However, it's important to note that this method may raise an exception, as seen in the following example:

```
"NISTu89":
  dimension_url: "#NISTd16"
  short:
  root: false
  unit_system:
    type: "non-SI_not_acceptable"
    name: "non-SI"
  unit_name:
    - "erg per second"
  unit_symbols:
    - id: "erg*s^-1"
      ascii: "erg*s^-1"
      html: "erg/s"
      mathml: "<mrow><mi mathvariant='normal'>erg</mi><mo>/</mo><mrow><mi mathvariant='normal'>s</mi></mrow>"
      latex: \ensuremath{\mathrm{erg/s}}
      unicode: "erg·s⁻¹"
  root_units:
    enumerated_root_units:
      - unit: "erg"
        power_denominator: 1
        power_numerator: 1
      - unit: "second"
        power_denominator: 1
        power_numerator: -1
  quantity_reference:
    - name: "power"
      url: "#NISTq20"
    - name: "radiant flux"
      url: "#NISTq21"
```
`mathml: "<mrow><mi mathvariant='normal'>erg</mi><mo>/</mo><mrow><mi mathvariant='normal'>s</mi></mrow>"`
In this example, one closing _mrow tag_ is missing, which will cause an exception when using the **Ox** parse method.

2023-05-11 23:01 UTC, ronaldtse commented
> We can use the Ox parse method to parse the unitsdb output, which includes the values of both the MathML and HTML keys in the units.yaml file.

MathML should be parsed properly via Plurimath.

We do not really need to parse HTML, but just offer the value.

e.g.
```ruby
Units.get_unit(:NISTu89).to_html
=> "erg/s"
Units.get_unit(:NISTu89).to_mathml
=> "<mrow><mi mathvariant='normal'>erg</mi><mo>/</mo><mrow><mi mathvariant='normal'>s</mi></mrow>"
Units.get_unit(:NISTu89).to_plurimath
=> Plurimath::Math
```

### Broken MathML

> mathml: `"<mrow><mi mathvariant='normal'>erg</mi><mo>/</mo><mrow><mi mathvariant='normal'>s</mi></mrow>"`
>
> In this example, one closing mrow tag is missing, which will cause an exception when using the Ox parse method.

We should fix this in UnitsDB. We should have a validation step (via rspec) that ensures all values in UnitsDB are valid.

2023-05-12 10:48 UTC, suleman-uzair commented
> We should fix this in UnitsDB. We should have a validation step (via rspec) that ensures all values in UnitsDB are valid.

Should we add the rspec test to the UnitsDB repo for the validation of MathML?

2023-05-12 11:03 UTC, ronaldtse commented
> Should we add the rspec test to the UnitsDB repo for the validation of MathML?

Yes please!

2023-05-13 12:36 UTC, ronaldtse commented
@suleman-uzair is this ready to merge now? Thanks.

2023-05-15 13:41 UTC, suleman-uzair commented
> @suleman-uzair is this ready to merge now? Thanks.

@ronaldtse , As we have made some changes to the **Unitsdb** **MathML** output, I am including **Ox** parsing functionality to generate the **MathML** in **Unitsml-Ruby**.

2023-05-17 01:50 UTC, ronaldtse requested changes

2023-05-17 01:50 UTC, ronaldtse commented on lib/unitsml.rb
> +Ox.default_options = { encoding: "UTF-8" }
This sets a global option and it's dangerous -- Ox is used also in other gems. I think the `unitsml` gem needs to use its own Ox instance.

2023-05-17 01:50 UTC, ronaldtse commented on lib/unitsml/formula.rb
> +        if term.is_a?(Unit)
Use a `case` `when` statement.

2023-05-17 01:50 UTC, ronaldtse commented on lib/unitsml/formula.rb
> +      <<~UNITSML
Use a `[].join`

2023-05-17 01:50 UTC, ronaldtse commented on lib/unitsml/formula.rb
> +      <<~XML
Use `[].join`

2023-05-17 01:50 UTC, ronaldtse commented on lib/unitsml/unit.rb
> +      if integer.match?(/-/)
Use an early return form:
```ruby
unless integer.match?(/-/)
  return mathml ? [Ox.parse("<mn>#{integer}</mn>")] : integer
end

if mathml
...
```

2023-05-17 09:02 UTC, suleman-uzair commented
@ronaldtse, I have completed the implementation of the changes. Please let me know if you would like me to proceed with merging.

2023-05-30 08:14 UTC, merged